#---------------------------------------#
#  Build the PSetManager.exe     #
#---------------------------------------#
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore "PSets\Tools\PSetManager\PSetManager.sln"
build:
  project: PSets\Tools\PSetManager\PSetManager.sln
  verbosity: minimal
artifacts:
- path: PSets\Tools\PSetManager\PSetManager\bin\$(configuration)
  name: PSetManager
- path: PSets\Tools\PSetManager\PSetManager\bin\$(configuration)\PSetManager.log
  name: PSet2YamlConverterLog
  
#---------------------------------------#
#    Run the PSetManager.exe     #
#---------------------------------------#
environment:
  access_token:
    secure: sNVOMaQLV0mfLGZL9mXDXZvRvhHjX+WYON1/WokLH7w2fev2upMCuElyw07vW1w0
  gh_email:
    secure: V/J9RJx75dwkZ3GYcz6HxOuHhgRjronD6QpRkF5O+so=
  gh_username: 
    secure: WYN/eo4TYe5gfE1sRt2Ugw==
  bsddUrl: http://test.bsdd.buildingsmart.org
  bsdd_username: 
    secure: V/J9RJx75dwkZ3GYcz6HxOuHhgRjronD6QpRkF5O+so=
  bsdd_password: 
    secure: NsrogBgtuwTGnsZJl37ryz5NPjIO7ZESEzqd+1Xcd9lpE3XW0LBaE9eGI3ModO0q    
  
on_finish:
  - ps: '& "C:\projects\bSDD\PSets\Tools\ConvertAndPublishPSets.ps1 -bsddUrl $env:bsddUrl -bsdd_username $env:bsdd_username -bsdd_password $env:bsdd_password"'
#  - git config --global credential.helper store
#  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
#  - git config --global user.email "$($env:gh_email)"
#  - git config --global user.name "$($env:gh_username)"
#  - git config core.autocrlf true
#  - git status
#  - git commit . -m "Transformed PSets to YAML and JSON format"
#  - git remote -v
#  - git push origin master